name: CI de Calidad de Código

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código del repositorio a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el entorno de Java (JDK) y el caché de Maven
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          # Habilita el caché para las dependencias de Maven, acelerando futuras ejecuciones
          cache: "maven"

      # 3. Ejecuta el comando de Maven para validar todo
      #    Este único comando realiza todas las validaciones que configuramos
      - name: Build with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean verify

      # 4. Sube los reportes si el build falla
      - name: Subir reportes en caso de fallo
        if: failure() # Este paso solo se ejecuta si el paso anterior falla
        uses: actions/upload-artifact@v4
        with:
          name: reportes-de-fallo
          path: target/site
